
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Program Files/Oculus/Support/oculus-runtime/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/"
      - "D:/home/1.app/1.software/NodeJS/"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "D:/home/1.app/1.software/CMake/bin/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "D:/home/1.app/1.software/usbipd/"
      - "C:/Program Files/Tailscale/"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/"
      - "D:/home/1.app/1.software/Python311/Scripts/"
      - "D:/home/1.app/1.software/Python311/"
      - "D:/home/1.app/1.software/Python313/Scripts/"
      - "D:/home/1.app/1.software/Python313/"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/rikuu/AppData/Roaming/npm/"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/"
      - "D:/home/1.app/1.software/Ollama/"
      - "D:/home/1.app/1.software/VSCode/bin/"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/"
      - "C:/Users/rikuu/AppData/Local/GitHubDesktop/bin/"
      - "D:/home/1.app/1.software/Antigravity/bin/"
      - "C:/Users/rikuu/AppData/Local/PowerToys/DSCModules/"
      - "C:/Users/rikuu/.antigravity/extensions/ms-python.debugpy-2025.14.1-win32-x64/bundled/scripts/noConfigScripts/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Program Files/Oculus/Support/oculus-runtime/mingw32-make.exe.com"
      - "C:/Program Files/Oculus/Support/oculus-runtime/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/mingw32-make.exe.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/mingw32-make.exe"
      - "D:/home/1.app/1.software/NodeJS/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/NodeJS/mingw32-make.exe"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/mingw32-make.exe.com"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/mingw32-make.exe"
      - "D:/home/1.app/1.software/CMake/bin/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/CMake/bin/mingw32-make.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe.com"
      - "C:/Program Files/Docker/Docker/resources/bin/mingw32-make.exe"
      - "D:/home/1.app/1.software/usbipd/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/usbipd/mingw32-make.exe"
      - "C:/Program Files/Tailscale/mingw32-make.exe.com"
      - "C:/Program Files/Tailscale/mingw32-make.exe"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/mingw32-make.exe.com"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/mingw32-make.exe"
      - "D:/home/1.app/1.software/Python311/Scripts/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/Python311/Scripts/mingw32-make.exe"
      - "D:/home/1.app/1.software/Python311/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/Python311/mingw32-make.exe"
      - "D:/home/1.app/1.software/Python313/Scripts/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/Python313/Scripts/mingw32-make.exe"
      - "D:/home/1.app/1.software/Python313/mingw32-make.exe.com"
      - "D:/home/1.app/1.software/Python313/mingw32-make.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/mingw32-make.exe.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/mingw32-make.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/rikuu/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/rikuu/AppData/Roaming/npm/mingw32-make.exe"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/mingw32-make.exe.com"
    found: "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/mingw32-make.exe"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Oculus\\Support\\oculus-runtime"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Programs\\Git\\cmd"
        - "D:\\home\\1.app\\1.software\\NodeJS\\"
        - "C:\\Program Files\\Rust stable MSVC 1.91\\bin"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "D:\\home\\1.app\\1.software\\CMake\\bin"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "D:\\home\\1.app\\1.software\\usbipd\\"
        - "C:\\Program Files\\Tailscale\\"
        - "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\12.2 mpacbti-rel1\\bin"
        - "D:\\home\\1.app\\1.software\\Python311\\Scripts\\"
        - "D:\\home\\1.app\\1.software\\Python311\\"
        - "D:\\home\\1.app\\1.software\\Python313\\Scripts\\"
        - "D:\\home\\1.app\\1.software\\Python313\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\rikuu\\AppData\\Roaming\\npm"
        - "D:\\home\\1.app\\1.software\\LLVM-MinGW\\llvm-mingw-20251118-ucrt-x86_64\\bin"
        - "D:\\home\\1.app\\1.software\\Ollama"
        - "D:\\home\\1.app\\1.software\\VSCode\\bin"
        - "C:\\Users\\rikuu\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\rikuu\\AppData\\Local\\GitHubDesktop\\bin"
        - "D:\\home\\1.app\\1.software\\Antigravity\\bin"
        - "C:\\Users\\rikuu\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "c:\\Users\\rikuu\\.antigravity\\extensions\\ms-python.debugpy-2025.14.1-win32-x64\\bundled\\scripts\\noConfigScripts"
...
