
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FindGit.cmake:111 (find_program)"
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1884 (find_package)"
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1619 (__FetchContent_populateSubbuild)"
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FetchContent.cmake:2155:EVAL:2 (__FetchContent_doPopulation)"
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FetchContent.cmake:2155 (cmake_language)"
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1988:EVAL:1 (__FetchContent_Populate)"
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/FetchContent.cmake:1988 (cmake_language)"
      - "pico_sdk_import.cmake:40 (FetchContent_Populate)"
      - "CMakeLists.txt:4 (include)"
    mode: "program"
    variable: "GIT_EXECUTABLE"
    description: "Git command line client"
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "git.cmd"
      - "git"
    candidate_directories:
      - "C:/Program Files/Oculus/Support/oculus-runtime/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/"
      - "D:/home/1.app/1.software/NodeJS/"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "D:/home/1.app/1.software/CMake/bin/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "D:/home/1.app/1.software/usbipd/"
      - "C:/Program Files/Tailscale/"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/"
      - "D:/home/1.app/1.software/Python311/Scripts/"
      - "D:/home/1.app/1.software/Python311/"
      - "D:/home/1.app/1.software/Python313/Scripts/"
      - "D:/home/1.app/1.software/Python313/"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/rikuu/AppData/Roaming/npm/"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/"
      - "D:/home/1.app/1.software/Ollama/"
      - "D:/home/1.app/1.software/VSCode/bin/"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/"
      - "C:/Users/rikuu/AppData/Local/GitHubDesktop/bin/"
      - "D:/home/1.app/1.software/Antigravity/bin/"
      - "C:/Users/rikuu/AppData/Local/PowerToys/DSCModules/"
      - "C:/Users/rikuu/.antigravity/extensions/ms-python.debugpy-2025.14.1-win32-x64/bundled/scripts/noConfigScripts/"
      - "C:/Users/rikuu/AppData/Local/Atlassian/SourceTree/git_local/bin/"
    searched_directories:
      - "C:/Program Files/Oculus/Support/oculus-runtime/git.cmd.com"
      - "C:/Program Files/Oculus/Support/oculus-runtime/git.cmd.exe"
      - "C:/Program Files/Oculus/Support/oculus-runtime/git.cmd"
      - "C:/Windows/System32/git.cmd.com"
      - "C:/Windows/System32/git.cmd.exe"
      - "C:/Windows/System32/git.cmd"
      - "C:/Windows/git.cmd.com"
      - "C:/Windows/git.cmd.exe"
      - "C:/Windows/git.cmd"
      - "C:/Windows/System32/wbem/git.cmd.com"
      - "C:/Windows/System32/wbem/git.cmd.exe"
      - "C:/Windows/System32/wbem/git.cmd"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.cmd"
      - "C:/Windows/System32/OpenSSH/git.cmd.com"
      - "C:/Windows/System32/OpenSSH/git.cmd.exe"
      - "C:/Windows/System32/OpenSSH/git.cmd"
      - "C:/Program Files/dotnet/git.cmd.com"
      - "C:/Program Files/dotnet/git.cmd.exe"
      - "C:/Program Files/dotnet/git.cmd"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/git.cmd"
      - "D:/home/1.app/1.software/NodeJS/git.cmd.com"
      - "D:/home/1.app/1.software/NodeJS/git.cmd.exe"
      - "D:/home/1.app/1.software/NodeJS/git.cmd"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/git.cmd.com"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/git.cmd.exe"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/git.cmd"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/git.cmd.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/git.cmd.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/git.cmd"
      - "D:/home/1.app/1.software/CMake/bin/git.cmd.com"
      - "D:/home/1.app/1.software/CMake/bin/git.cmd.exe"
      - "D:/home/1.app/1.software/CMake/bin/git.cmd"
      - "C:/Program Files/Docker/Docker/resources/bin/git.cmd.com"
      - "C:/Program Files/Docker/Docker/resources/bin/git.cmd.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/git.cmd"
      - "D:/home/1.app/1.software/usbipd/git.cmd.com"
      - "D:/home/1.app/1.software/usbipd/git.cmd.exe"
      - "D:/home/1.app/1.software/usbipd/git.cmd"
      - "C:/Program Files/Tailscale/git.cmd.com"
      - "C:/Program Files/Tailscale/git.cmd.exe"
      - "C:/Program Files/Tailscale/git.cmd"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/git.cmd.com"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/git.cmd.exe"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/git.cmd"
      - "D:/home/1.app/1.software/Python311/Scripts/git.cmd.com"
      - "D:/home/1.app/1.software/Python311/Scripts/git.cmd.exe"
      - "D:/home/1.app/1.software/Python311/Scripts/git.cmd"
      - "D:/home/1.app/1.software/Python311/git.cmd.com"
      - "D:/home/1.app/1.software/Python311/git.cmd.exe"
      - "D:/home/1.app/1.software/Python311/git.cmd"
      - "D:/home/1.app/1.software/Python313/Scripts/git.cmd.com"
      - "D:/home/1.app/1.software/Python313/Scripts/git.cmd.exe"
      - "D:/home/1.app/1.software/Python313/Scripts/git.cmd"
      - "D:/home/1.app/1.software/Python313/git.cmd.com"
      - "D:/home/1.app/1.software/Python313/git.cmd.exe"
      - "D:/home/1.app/1.software/Python313/git.cmd"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/git.cmd"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/git.cmd"
      - "C:/Users/rikuu/AppData/Roaming/npm/git.cmd.com"
      - "C:/Users/rikuu/AppData/Roaming/npm/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Roaming/npm/git.cmd"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/git.cmd.com"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/git.cmd.exe"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/git.cmd"
      - "D:/home/1.app/1.software/Ollama/git.cmd.com"
      - "D:/home/1.app/1.software/Ollama/git.cmd.exe"
      - "D:/home/1.app/1.software/Ollama/git.cmd"
      - "D:/home/1.app/1.software/VSCode/bin/git.cmd.com"
      - "D:/home/1.app/1.software/VSCode/bin/git.cmd.exe"
      - "D:/home/1.app/1.software/VSCode/bin/git.cmd"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/git.cmd"
      - "C:/Users/rikuu/AppData/Local/GitHubDesktop/bin/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/GitHubDesktop/bin/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/GitHubDesktop/bin/git.cmd"
      - "D:/home/1.app/1.software/Antigravity/bin/git.cmd.com"
      - "D:/home/1.app/1.software/Antigravity/bin/git.cmd.exe"
      - "D:/home/1.app/1.software/Antigravity/bin/git.cmd"
      - "C:/Users/rikuu/AppData/Local/PowerToys/DSCModules/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/PowerToys/DSCModules/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/PowerToys/DSCModules/git.cmd"
      - "C:/Users/rikuu/.antigravity/extensions/ms-python.debugpy-2025.14.1-win32-x64/bundled/scripts/noConfigScripts/git.cmd.com"
      - "C:/Users/rikuu/.antigravity/extensions/ms-python.debugpy-2025.14.1-win32-x64/bundled/scripts/noConfigScripts/git.cmd.exe"
      - "C:/Users/rikuu/.antigravity/extensions/ms-python.debugpy-2025.14.1-win32-x64/bundled/scripts/noConfigScripts/git.cmd"
      - "C:/Users/rikuu/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd.com"
      - "C:/Users/rikuu/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd.exe"
      - "C:/Users/rikuu/AppData/Local/Atlassian/SourceTree/git_local/bin/git.cmd"
      - "C:/Program Files/Oculus/Support/oculus-runtime/git.com"
      - "C:/Program Files/Oculus/Support/oculus-runtime/git.exe"
      - "C:/Program Files/Oculus/Support/oculus-runtime/git"
      - "C:/Windows/System32/git.com"
      - "C:/Windows/System32/git.exe"
      - "C:/Windows/System32/git"
      - "C:/Windows/git.com"
      - "C:/Windows/git.exe"
      - "C:/Windows/git"
      - "C:/Windows/System32/wbem/git.com"
      - "C:/Windows/System32/wbem/git.exe"
      - "C:/Windows/System32/wbem/git"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/git"
      - "C:/Windows/System32/OpenSSH/git.com"
      - "C:/Windows/System32/OpenSSH/git.exe"
      - "C:/Windows/System32/OpenSSH/git"
      - "C:/Program Files/dotnet/git.com"
      - "C:/Program Files/dotnet/git.exe"
      - "C:/Program Files/dotnet/git"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/git.com"
    found: "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/git.exe"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Oculus\\Support\\oculus-runtime"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Programs\\Git\\cmd"
        - "D:\\home\\1.app\\1.software\\NodeJS\\"
        - "C:\\Program Files\\Rust stable MSVC 1.91\\bin"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "D:\\home\\1.app\\1.software\\CMake\\bin"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "D:\\home\\1.app\\1.software\\usbipd\\"
        - "C:\\Program Files\\Tailscale\\"
        - "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\12.2 mpacbti-rel1\\bin"
        - "D:\\home\\1.app\\1.software\\Python311\\Scripts\\"
        - "D:\\home\\1.app\\1.software\\Python311\\"
        - "D:\\home\\1.app\\1.software\\Python313\\Scripts\\"
        - "D:\\home\\1.app\\1.software\\Python313\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\rikuu\\AppData\\Roaming\\npm"
        - "D:\\home\\1.app\\1.software\\LLVM-MinGW\\llvm-mingw-20251118-ucrt-x86_64\\bin"
        - "D:\\home\\1.app\\1.software\\Ollama"
        - "D:\\home\\1.app\\1.software\\VSCode\\bin"
        - "C:\\Users\\rikuu\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\rikuu\\AppData\\Local\\GitHubDesktop\\bin"
        - "D:\\home\\1.app\\1.software\\Antigravity\\bin"
        - "C:\\Users\\rikuu\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "c:\\Users\\rikuu\\.antigravity\\extensions\\ms-python.debugpy-2025.14.1-win32-x64\\bundled\\scripts\\noConfigScripts"
...
