
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "D:/home/1.app/1.software/CMake/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Program Files/Oculus/Support/oculus-runtime/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/"
      - "D:/home/1.app/1.software/NodeJS/"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "D:/home/1.app/1.software/CMake/bin/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "D:/home/1.app/1.software/usbipd/"
      - "C:/Program Files/Tailscale/"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/"
      - "D:/home/1.app/1.software/Python311/Scripts/"
      - "D:/home/1.app/1.software/Python311/"
      - "D:/home/1.app/1.software/Python313/Scripts/"
      - "D:/home/1.app/1.software/Python313/"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/rikuu/AppData/Roaming/npm/"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/"
      - "D:/home/1.app/1.software/Ollama/"
      - "D:/home/1.app/1.software/VSCode/bin/"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/"
      - "C:/Users/rikuu/AppData/Local/GitHubDesktop/bin/"
      - "D:/home/1.app/1.software/Antigravity/bin/"
      - "C:/Users/rikuu/AppData/Local/PowerToys/DSCModules/"
      - "C:/Users/rikuu/.antigravity/extensions/ms-python.debugpy-2025.14.1-win32-x64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "C:/Program Files/Oculus/Support/oculus-runtime/ninja-build.com"
      - "C:/Program Files/Oculus/Support/oculus-runtime/ninja-build.exe"
      - "C:/Program Files/Oculus/Support/oculus-runtime/ninja-build"
      - "C:/Program Files/Oculus/Support/oculus-runtime/ninja.com"
      - "C:/Program Files/Oculus/Support/oculus-runtime/ninja.exe"
      - "C:/Program Files/Oculus/Support/oculus-runtime/ninja"
      - "C:/Program Files/Oculus/Support/oculus-runtime/samu.com"
      - "C:/Program Files/Oculus/Support/oculus-runtime/samu.exe"
      - "C:/Program Files/Oculus/Support/oculus-runtime/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/ninja-build.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/ninja-build.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/ninja-build"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/ninja.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/ninja.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/ninja"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/samu.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/samu.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Git/cmd/samu"
      - "D:/home/1.app/1.software/NodeJS/ninja-build.com"
      - "D:/home/1.app/1.software/NodeJS/ninja-build.exe"
      - "D:/home/1.app/1.software/NodeJS/ninja-build"
      - "D:/home/1.app/1.software/NodeJS/ninja.com"
      - "D:/home/1.app/1.software/NodeJS/ninja.exe"
      - "D:/home/1.app/1.software/NodeJS/ninja"
      - "D:/home/1.app/1.software/NodeJS/samu.com"
      - "D:/home/1.app/1.software/NodeJS/samu.exe"
      - "D:/home/1.app/1.software/NodeJS/samu"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/ninja-build.com"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/ninja-build.exe"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/ninja-build"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/ninja.com"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/ninja.exe"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/ninja"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/samu.com"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/samu.exe"
      - "C:/Program Files/Rust stable MSVC 1.91/bin/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "D:/home/1.app/1.software/CMake/bin/ninja-build.com"
      - "D:/home/1.app/1.software/CMake/bin/ninja-build.exe"
      - "D:/home/1.app/1.software/CMake/bin/ninja-build"
      - "D:/home/1.app/1.software/CMake/bin/ninja.com"
      - "D:/home/1.app/1.software/CMake/bin/ninja.exe"
      - "D:/home/1.app/1.software/CMake/bin/ninja"
      - "D:/home/1.app/1.software/CMake/bin/samu.com"
      - "D:/home/1.app/1.software/CMake/bin/samu.exe"
      - "D:/home/1.app/1.software/CMake/bin/samu"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.com"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/samu"
      - "D:/home/1.app/1.software/usbipd/ninja-build.com"
      - "D:/home/1.app/1.software/usbipd/ninja-build.exe"
      - "D:/home/1.app/1.software/usbipd/ninja-build"
      - "D:/home/1.app/1.software/usbipd/ninja.com"
      - "D:/home/1.app/1.software/usbipd/ninja.exe"
      - "D:/home/1.app/1.software/usbipd/ninja"
      - "D:/home/1.app/1.software/usbipd/samu.com"
      - "D:/home/1.app/1.software/usbipd/samu.exe"
      - "D:/home/1.app/1.software/usbipd/samu"
      - "C:/Program Files/Tailscale/ninja-build.com"
      - "C:/Program Files/Tailscale/ninja-build.exe"
      - "C:/Program Files/Tailscale/ninja-build"
      - "C:/Program Files/Tailscale/ninja.com"
      - "C:/Program Files/Tailscale/ninja.exe"
      - "C:/Program Files/Tailscale/ninja"
      - "C:/Program Files/Tailscale/samu.com"
      - "C:/Program Files/Tailscale/samu.exe"
      - "C:/Program Files/Tailscale/samu"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/ninja-build.com"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/ninja-build.exe"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/ninja-build"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/ninja.com"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/ninja.exe"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/ninja"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/samu.com"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/samu.exe"
      - "C:/Program Files (x86)/Arm GNU Toolchain arm-none-eabi/12.2 mpacbti-rel1/bin/samu"
      - "D:/home/1.app/1.software/Python311/Scripts/ninja-build.com"
      - "D:/home/1.app/1.software/Python311/Scripts/ninja-build.exe"
      - "D:/home/1.app/1.software/Python311/Scripts/ninja-build"
      - "D:/home/1.app/1.software/Python311/Scripts/ninja.com"
      - "D:/home/1.app/1.software/Python311/Scripts/ninja.exe"
      - "D:/home/1.app/1.software/Python311/Scripts/ninja"
      - "D:/home/1.app/1.software/Python311/Scripts/samu.com"
      - "D:/home/1.app/1.software/Python311/Scripts/samu.exe"
      - "D:/home/1.app/1.software/Python311/Scripts/samu"
      - "D:/home/1.app/1.software/Python311/ninja-build.com"
      - "D:/home/1.app/1.software/Python311/ninja-build.exe"
      - "D:/home/1.app/1.software/Python311/ninja-build"
      - "D:/home/1.app/1.software/Python311/ninja.com"
      - "D:/home/1.app/1.software/Python311/ninja.exe"
      - "D:/home/1.app/1.software/Python311/ninja"
      - "D:/home/1.app/1.software/Python311/samu.com"
      - "D:/home/1.app/1.software/Python311/samu.exe"
      - "D:/home/1.app/1.software/Python311/samu"
      - "D:/home/1.app/1.software/Python313/Scripts/ninja-build.com"
      - "D:/home/1.app/1.software/Python313/Scripts/ninja-build.exe"
      - "D:/home/1.app/1.software/Python313/Scripts/ninja-build"
      - "D:/home/1.app/1.software/Python313/Scripts/ninja.com"
      - "D:/home/1.app/1.software/Python313/Scripts/ninja.exe"
      - "D:/home/1.app/1.software/Python313/Scripts/ninja"
      - "D:/home/1.app/1.software/Python313/Scripts/samu.com"
      - "D:/home/1.app/1.software/Python313/Scripts/samu.exe"
      - "D:/home/1.app/1.software/Python313/Scripts/samu"
      - "D:/home/1.app/1.software/Python313/ninja-build.com"
      - "D:/home/1.app/1.software/Python313/ninja-build.exe"
      - "D:/home/1.app/1.software/Python313/ninja-build"
      - "D:/home/1.app/1.software/Python313/ninja.com"
      - "D:/home/1.app/1.software/Python313/ninja.exe"
      - "D:/home/1.app/1.software/Python313/ninja"
      - "D:/home/1.app/1.software/Python313/samu.com"
      - "D:/home/1.app/1.software/Python313/samu.exe"
      - "D:/home/1.app/1.software/Python313/samu"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/ninja-build.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/ninja-build.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/ninja-build"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/ninja.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/ninja.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/ninja"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/samu.com"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/samu.exe"
      - "C:/Users/rikuu/AppData/Local/Programs/Python/Launcher/samu"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/rikuu/AppData/Roaming/npm/ninja-build.com"
      - "C:/Users/rikuu/AppData/Roaming/npm/ninja-build.exe"
      - "C:/Users/rikuu/AppData/Roaming/npm/ninja-build"
      - "C:/Users/rikuu/AppData/Roaming/npm/ninja.com"
      - "C:/Users/rikuu/AppData/Roaming/npm/ninja.exe"
      - "C:/Users/rikuu/AppData/Roaming/npm/ninja"
      - "C:/Users/rikuu/AppData/Roaming/npm/samu.com"
      - "C:/Users/rikuu/AppData/Roaming/npm/samu.exe"
      - "C:/Users/rikuu/AppData/Roaming/npm/samu"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/ninja-build.com"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/ninja-build.exe"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/ninja-build"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/ninja.com"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/ninja.exe"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/ninja"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/samu.com"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/samu.exe"
      - "D:/home/1.app/1.software/LLVM-MinGW/llvm-mingw-20251118-ucrt-x86_64/bin/samu"
      - "D:/home/1.app/1.software/Ollama/ninja-build.com"
      - "D:/home/1.app/1.software/Ollama/ninja-build.exe"
      - "D:/home/1.app/1.software/Ollama/ninja-build"
      - "D:/home/1.app/1.software/Ollama/ninja.com"
      - "D:/home/1.app/1.software/Ollama/ninja.exe"
      - "D:/home/1.app/1.software/Ollama/ninja"
      - "D:/home/1.app/1.software/Ollama/samu.com"
      - "D:/home/1.app/1.software/Ollama/samu.exe"
      - "D:/home/1.app/1.software/Ollama/samu"
      - "D:/home/1.app/1.software/VSCode/bin/ninja-build.com"
      - "D:/home/1.app/1.software/VSCode/bin/ninja-build.exe"
      - "D:/home/1.app/1.software/VSCode/bin/ninja-build"
      - "D:/home/1.app/1.software/VSCode/bin/ninja.com"
      - "D:/home/1.app/1.software/VSCode/bin/ninja.exe"
      - "D:/home/1.app/1.software/VSCode/bin/ninja"
      - "D:/home/1.app/1.software/VSCode/bin/samu.com"
      - "D:/home/1.app/1.software/VSCode/bin/samu.exe"
      - "D:/home/1.app/1.software/VSCode/bin/samu"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/ninja-build.com"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/ninja-build.exe"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/ninja-build"
      - "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/ninja.com"
    found: "C:/Users/rikuu/AppData/Local/Microsoft/WinGet/Links/ninja.exe"
    search_context:
      ENV{PATH}:
        - "C:\\Program Files\\Oculus\\Support\\oculus-runtime"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Programs\\Git\\cmd"
        - "D:\\home\\1.app\\1.software\\NodeJS\\"
        - "C:\\Program Files\\Rust stable MSVC 1.91\\bin"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "D:\\home\\1.app\\1.software\\CMake\\bin"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "D:\\home\\1.app\\1.software\\usbipd\\"
        - "C:\\Program Files\\Tailscale\\"
        - "C:\\Program Files (x86)\\Arm GNU Toolchain arm-none-eabi\\12.2 mpacbti-rel1\\bin"
        - "D:\\home\\1.app\\1.software\\Python311\\Scripts\\"
        - "D:\\home\\1.app\\1.software\\Python311\\"
        - "D:\\home\\1.app\\1.software\\Python313\\Scripts\\"
        - "D:\\home\\1.app\\1.software\\Python313\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Programs\\Python\\Launcher\\"
        - "C:\\Users\\rikuu\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\rikuu\\AppData\\Roaming\\npm"
        - "D:\\home\\1.app\\1.software\\LLVM-MinGW\\llvm-mingw-20251118-ucrt-x86_64\\bin"
        - "D:\\home\\1.app\\1.software\\Ollama"
        - "D:\\home\\1.app\\1.software\\VSCode\\bin"
        - "C:\\Users\\rikuu\\AppData\\Local\\Microsoft\\WinGet\\Links"
        - "C:\\Users\\rikuu\\AppData\\Local\\GitHubDesktop\\bin"
        - "D:\\home\\1.app\\1.software\\Antigravity\\bin"
        - "C:\\Users\\rikuu\\AppData\\Local\\PowerToys\\DSCModules\\"
        - "c:\\Users\\rikuu\\.antigravity\\extensions\\ms-python.debugpy-2025.14.1-win32-x64\\bundled\\scripts\\noConfigScripts"
...
